### ISSUE TITLE
Set basckground picture on section "about"

### ISSUE THREAD

**Issue by saram88** [saram88/fst-weseeu#7]
EPIC  <epic>

**Accepted criterias**

- [ ] Load up picrure 
- [ ] Set up code in HTML
- [ ] Set up style in CSS

**Task**
